# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml

dockerRegistry: gcr.io

jenkins-x-platform:
  dockerRegistry: gcr.io

  PipelineSecrets:

    # lets enable GCR docker builds
    DockerConfig: |-
      {
          "credHelpers": {
              "gcr.io": "gcr",
              "us.gcr.io": "gcr",
              "eu.gcr.io": "gcr",
              "asia.gcr.io": "gcr",
              "staging-k8s.gcr.io": "gcr"
          }
      }

docker-registry:
  enabled: false

